spring.application.name=charcuterie-orders

spring.datasource.url=jdbc:postgresql://localhost:5432/charcuterie
spring.datasource.username=char_user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.hibernate.SQL=DEBUG
logging.level.fr.julien.charcuterieorders=INFO

spring.jpa.properties.hibernate.jdbc.time_zone=Europe/Paris